Add changes to index.ts of Spirit Strategy
Error: src/strategies/spirit/index.ts(19,5): error TS2588: Cannot assign to 'contract_code' because it is a constant.
Error: src/strategies/spirit/index.ts(23,7): error TS2588: Cannot assign to 'lowest_block' because it is a constant.
Error: src/strategies/spirit/index.ts(32,58): error TS2300: Duplicate identifier 'block'.
Error: src/strategies/spirit/index.ts(33,9): error TS2300: Duplicate identifier 'block'.

All this errors are resolved.