Add fight-club strategy [fight-club] (#782)
* Copy erc20-balance-of and rename to fight-club/

* Fix tests

* Empty commit to re-run CI

  - CI depends on PR_TITLE, I just updated it so tests should run

* Update author and version

* Update examples.json

* Update schema.json

* Start hacking on fight-club index.ts

* console log debug: TypeError: options.gloves.forEach is not a function

* Tweak console log. prints object.  Why doesn't forEach work?

* Only look at 1 "glove" NFT

* Test on Mumbai

* Try to console.log the result of glove balanceOf multicall

* Remove unneeded console.log and forEach captured arg

* Increase glove weight to 8

* Remove unused captured arg

* Add calls to weightClass erc-1155 balanceOf

  - Fails with error:
    unexpected tokens (argument="value", value="balanceOf (address account, uint256 id) external view returns (uint256) ;", code=INVALID_ARGUMENT, version=abi/5.6.4)
  - Maybe can't specify ERC721 balanceOf in same ABI array as ERC1155
    balanceOf??

* Update example weightClass weights

* Use a much more recent block

* Use addresses.forEach and addresses.map

* Fix abi to differentiate ERC721 balanceOf and ERC1155 balanceOf

* Modify results in place, applying weights

* Observe that editing in place doesn't persist

* Try changing from const to let.  Didn't work

* Revert "Try changing from const to let.  Didn't work"

This reverts commit 1857ffc7603f849d82ddc81904f7b4816e8f4fb5.

* Build weightedResult object withour errors, but structure isn't right.

* Make weightedResult look more like result

* Use toNumber() in preparation for using Math.max()

* Add logic to multiply max glove with max weight class Kudo.

  * fix errors in weightedResult type BigNumber -> number
  * fix weightClass key (was "weightedClassess")

* Remove commented lines. formatUnits not needed

* Use checksum addresses in examples.json

* Rename weightClassTokenIds to weightClassIds

* yarn lint

* Improve logging. Remove unnecessary logging

* weight class multiplier = 1 if voter has no weight class kudos

* Improve fight-club README

* Rename options.gloves to options.gloveAddresses

* fixup! Rename options.gloves to options.gloveAddresses

* Switch to using NFTs and 1155s on ethereum mainnet for testing.

  - Mumbai RPC doesn't support archive node queries.

* If a user has >=1 nft or kudo, then only 1 is counted.

* Improve comments

* Adjust console logs

* Change title to match parameter name

* Delete fight-club schema.json

  - "type": "object" parameters don't render in snapshot playground,
    evidenced by safety-module-bpt-power.

* Update README to match examples.json

* yarn lint

* Change equation to use `score` instead of `power`

* Fix formatting

* Comment out console logging

* Limit gloves and weight class ids to 10.